In [2]:
#data cleaning of the datasets
import pandas as pd

In [4]:
#define paths to the dataset
path_1 = "DatasetforDataAnalytics.csv"

# Print it to verify
print(f'We will load data from: "{path_1}"')

We will load data from: "DatasetforDataAnalytics.csv"

In [5]:
# Load the dataset using the variable we defined
(
    pd.read_csv(path_1)
)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,ORD201195,2024-06-20,C21126,Desk,1,107.04,392 Main St,Credit Card,Cancelled,TRK38009181,6,FREESHIP,Google,107.04
1196,ORD201196,2024-03-04,C20095,Monitor,2,662.53,778 Main St,Online,Cancelled,TRK69207593,5,NaN,Facebook,1325.06
1197,ORD201197,2023-07-13,C79674,Tablet,2,436.84,275 Main St,Online,Delivered,TRK88039356,2,FREESHIP,Instagram,873.68
1198,ORD201198,2024-08-22,C64753,Chair,4,262.52,509 Main St,Debit Card,Cancelled,TRK71683331,4,WINTER15,Instagram,1050.08
1199,ORD201199,2023-06-11,C57502,Tablet,4,560.58,201 Main St,Gift Card,Returned,TRK51116746,6,SAVE10,Referral,2242.32

In [6]:
(
    pd.read_csv(path_1)
    .head()
)

,OrderID,Date,CustomerID,Product,Quantity,UnitPrice,ShippingAddress,PaymentMethod,OrderStatus,TrackingNumber,ItemsInCart,CouponCode,ReferralSource,TotalPrice
0,ORD200000,2023-01-04,C72649,Monitor,5,570.62,928 Main St,Debit Card,Shipped,TRK37947903,7,SAVE10,Instagram,2853.10
1,ORD200001,2024-08-23,C75739,Phone,2,151.35,823 Main St,Online,Shipped,TRK91186779,3,SAVE10,Referral,302.70
2,ORD200002,2024-02-27,C81728,Tablet,5,550.68,512 Main St,Credit Card,Cancelled,TRK42903982,8,FREESHIP,Email,2753.40
3,ORD200003,2023-10-15,C33540,Chair,1,273.19,275 Main St,Debit Card,Returned,TRK62788070,5,SAVE10,Facebook,273.19
4,ORD200004,2025-05-08,C81840,Printer,4,626.01,668 Main St,Online,Delivered,TRK29241424,8,SAVE10,Email,2504.04

In [7]:
(
    pd.read_csv(path_1)
    .shape
)

(1200, 14)

In [8]:
(
    pd.read_csv(path_1)
    .info()
)

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   str
 1   Date             1200 non-null   str
 2   CustomerID       1200 non-null   str
 3   Product          1200 non-null   str
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   str
 7   PaymentMethod    1200 non-null   str
 8   OrderStatus      1200 non-null   str
 9   TrackingNumber   1200 non-null   str
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       891 non-null    str
 12  ReferralSource   1200 non-null   str
 13  TotalPrice       1200 non-null   float64
dtypes: float64(2), int64(2), str(10)
memory usage: 131.4 KB

In [9]:
(
    pd.read_csv(path_1)
    .dtypes
)

OrderID                str
Date                   str
CustomerID             str
Product                str
Quantity             int64
UnitPrice          float64
ShippingAddress        str
PaymentMethod          str
OrderStatus            str
TrackingNumber         str
ItemsInCart          int64
CouponCode             str
ReferralSource         str
TotalPrice         float64
dtype: object

In [10]:
# where exactly are the missing values

(
    pd.read_csv(path_1)
    .isnull()
    .sum()
)

OrderID              0
Date                 0
CustomerID           0
Product              0
Quantity             0
UnitPrice            0
ShippingAddress      0
PaymentMethod        0
OrderStatus          0
TrackingNumber       0
ItemsInCart          0
CouponCode         309
ReferralSource       0
TotalPrice           0
dtype: int64

In [15]:
# Inspecting the key columns
# We open a parenthesis to start a "chain" across multiple lines
# CouponCode has 309 missing values, however not all products have coupon cddes - we wil replce with a placeholder "No coupon"
# convert date to datetime type
# convert OrderID, CustomerID, properly to string type
# convert OrderStatus, ReferralSource to category type
df_clean = (
    pd.read_csv(path_1)
    .assign(
        # 1. Fill missing CouponCode with placeholder
        CouponCode = lambda x: 
        x["CouponCode"].fillna("No coupon"),
        
        # 2. Safe Date conversion
        Date = lambda x: 
        pd.to_datetime(x["Date"], errors="coerce"),
        
        # 3. Ensure IDs are strings
        OrderID = lambda x: 
        x["OrderID"].astype(str),
        CustomerID = lambda x: 
        x["CustomerID"].astype(str),
        
        # 4. Convert repetitive text fields to categories
        OrderStatus = lambda x: 
        x["OrderStatus"].astype("category"),
        ReferralSource = lambda x: 
        x["ReferralSource"].astype("category")
    )
)

# Quickly inspect the new dtypes and missing values to verify!
print(df_clean.info())

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   OrderID          1200 non-null   str
 1   Date             1200 non-null   datetime64[us]
 2   CustomerID       1200 non-null   str
 3   Product          1200 non-null   str
 4   Quantity         1200 non-null   int64
 5   UnitPrice        1200 non-null   float64
 6   ShippingAddress  1200 non-null   str
 7   PaymentMethod    1200 non-null   str
 8   OrderStatus      1200 non-null   category
 9   TrackingNumber   1200 non-null   str
 10  ItemsInCart      1200 non-null   int64
 11  CouponCode       1200 non-null   str
 12  ReferralSource   1200 non-null   category
 13  TotalPrice       1200 non-null   float64
dtypes: category(2), datetime64[us](1), float64(2), int64(2), str(7)
memory usage: 115.1 KB
None

In [17]:
df_clean.describe()

                      Date     Quantity    UnitPrice  ItemsInCart   TotalPrice
count                 1200  1200.000000  1200.000000  1200.000000  1200.000000
mean   2024-03-22 16:58:48     2.945833   356.412750     5.485000  1053.968300
min    2023-01-01 00:00:00     1.000000    11.390000     1.000000    11.390000
25%    2023-08-03 18:00:00     2.000000   186.062500     4.000000   410.520000
50%    2024-03-23 00:00:00     3.000000   364.210000     5.000000   823.615000
75%    2024-11-08 12:00:00     4.000000   521.570000     7.000000  1578.475000
max    2025-06-30 00:00:00     5.000000   699.930000    10.000000  3456.400000
std                    NaN     1.407557   197.177146     2.281983   819.856558

In [28]:
# Find all string/object columns
string_cols = df_clean.select_dtypes(include=['str', 'object', 'category']).columns

# Count how many rows have leading/trailing spaces in each column
for col in string_cols:
    space_count = df_clean[col].astype(str).str.contains(r'^\s+|\s+$', regex=True).sum()
    if space_count > 0:
        print(f"Column '{col}' has {space_count} rows with leading/trailing spaces.")
    else:
        print(f"✅ '{col}' is perfectly clean!")

✅ 'OrderID' is perfectly clean!
✅ 'CustomerID' is perfectly clean!
✅ 'Product' is perfectly clean!
✅ 'ShippingAddress' is perfectly clean!
✅ 'PaymentMethod' is perfectly clean!
✅ 'OrderStatus' is perfectly clean!
✅ 'TrackingNumber' is perfectly clean!
✅ 'CouponCode' is perfectly clean!
✅ 'ReferralSource' is perfectly clean!

In [29]:
# Calculate structural distributions
skewness = df_clean[['Quantity', 'UnitPrice', 'ItemsInCart', 'TotalPrice']].skew()

print("--- Skewness Coefficients ---")
print(skewness)
print("\nAnalytical Note: A value > 1 indicates highly right-skewed data, meaning outliers pull the mean away from the truth.")

--- Skewness Coefficients ---
Quantity       0.027922
UnitPrice     -0.026512
ItemsInCart    0.000877
TotalPrice     0.891359
dtype: float64

Analytical Note: A value > 1 indicates highly right-skewed data, meaning outliers pull the mean away from the truth.